FROM node:14.15.5

WORKDIR /www

# Copy the complete repository to the /www folder
COPY . /www

# Install all the required packages
RUN rm -rf node_modules
RUN npm install

# Expose the development port
EXPOSE 8080

CMD ["npm", "run", "serve"]
